# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: karpentercrd
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/junchil/eks-cluster.git
#     targetRevision: main
#     path: infra/helm/karpenter-crd
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: karpenter
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
