apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-goprometheus
spec:
  ports:
    - name: tcp-goprometheus
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: goprometheus