dist: xenial
language: python

services:
  - docker

env:
  global:
    - LOCAL_BIN=${HOME}/.local/bin # For downloaded tools like terraform and awscli
    # Retrieve commit tag values for each micro-service folder to be used in tagging and deploying docker images.
    # Dependency folders are included as well and must be maintained
    - APP_TAG=$(git log --pretty=format:rc-%h -n 1 -- app)
    - TESTBOX_TAG=$(git log --pretty=format:rc-%h -n 1 -- app)

before_install:
  - mkdir -p ${LOCAL_BIN}
  - export PATH=${PATH}:${LOCAL_BIN}    # Put aws in the path
  - git config --global url.git@github.com:.insteadOf https://github.com/
  - make common-deps                    # install dependencies from Makefile in the root


script:
  - set -e               # Stop script immediately on error
  - cd $SERVICE_DIR
  - export AWS_PROFILE=${TARGET_AWS_PROFILE}
  - make check-image-exists && travis_terminate 0 || echo "Image doesn't exist, continue with build process";
  - make publish         # Publish will do the build

# This governs the order of stage-execution
stages:
  - name: build
  - name: deployment

jobs:
  include:
    - stage: build
      name: "✍️ REA WEB SERVER: Build, test and publish the image"
      env:
        - SERVICE_DIR=app
        - TARGET_AWS_PROFILE=AWS_STEVE
        - COMMIT_HASH=${REA_APP_TAG}
      if: (branch = tag AND tag =~ /v\d+.\d+(.\d+)?/) OR (branch != tag)