apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: "AL2"
  role: "anycluster-karpenter-node-role" # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "anycluster" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "anycluster" # replace with your cluster name