apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: "KarpenterNodeRole-anycluster" # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "anycluster" # replace with your cluster name
#   securityGroupSelectorTerms:
#     - tags:
#         karpenter.sh/discovery: "anycluster" # replace with your cluster name