apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-golang-app-vs
  namespace: app
spec:
  hosts:
    - {{ .Release.Name }}-golang-app
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}-golang-app
        subset: v1
      weight: 100
    - destination:
        host: {{ .Release.Name }}-golang-app
        subset: v2
      weight: 0
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Release.Name }}-golang-app
  - match:
    - uri:
        prefix: /info
    route:
    - destination:
        host: {{ .Release.Name }}-golang-app
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-golang-app-dr
  namespace: app
spec:
  host: {{ .Release.Name }}-golang-app
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2