apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-golang-app
  namespace: app
  labels:
    app: {{ .Release.Name }}-golang-app
spec:
  ports:
    - name: tcp-golang-app
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: NodePort
  selector:
    app: {{ .Release.Name }}-golang-app