apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-golang-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: golang-app