apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-golang-app
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app: golang-app