apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-golang-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /golang
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-golang-app
            port:
              number: 8080
      - path: /golang/info
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-golang-app
            port:
              number: 8080