apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-golang-app
  namespace: app
  labels:
    app: {{ .Release.Name }}-golang-app
spec:
  gateways:
  - {{ .Release.Name }}-golang-app-gateway
  hosts:
  - "web.stevejcliu.com"
  http:
  - match:
    - uri:
        prefix: /
    # - uri:
    #     prefix: /golang($|/)(.*)
    route:
    - destination:
        host: {{ .Release.Name }}-golang-app
        subset: v1
      weight: 100
    - destination:
        host: {{ .Release.Name }}-golang-app
        subset: v2
      weight: 0
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-golang-app
  namespace: app
  labels:
    app: {{ .Release.Name }}-golang-app
spec:
  host: {{ .Release.Name }}-golang-app
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2