apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-golang-app
  namespace: app
  labels:
    app: {{ .Release.Name }}-golang-app
spec:
  gateways:
  - {{ .Release.Name }}-golang-app-gateway
  hosts:
  - "web.stevejcliu.com"
  http:
  - match:
    - uri:
        prefix: /golang
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ .Release.Name }}-golang-app
        subset: v1
      weight: 75
    - destination:
        host: {{ .Release.Name }}-golang-app
        subset: v2
      weight: 25
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-golang-app
  namespace: app
  labels:
    app: {{ .Release.Name }}-golang-app
spec:
  host: {{ .Release.Name }}-golang-app-service
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 100
  - name: v2
    labels:
      version: v2
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 100