{{- if .Values.nginx.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-golang-app
spec:
  ingressClassName: nginx
  rules:
  - host: web.stevejcliu.com
    http:
      paths:
      - path: /golang
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-golang-app-service
            port:
              number: 8081
{{- end -}}