apiVersion: v2
description: A Helm chart for Kubernetes
name: eksapp-external-dns
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
- name: external-dns
  version: 6.28.4
  repository: https://charts.bitnami.com/bitnami
  alias: externaldns
  condition: externaldns.enabled