environment: Default

testBox:
  enabled: true
  image:
    repository: 675617749633.dkr.ecr.ap-southeast-2.amazonaws.com/eks-cluster/testbox
    tag: latest
    pullPolicy: Always
  replicas: 1

pythonApp:
  image:
    repository: 675617749633.dkr.ecr.ap-southeast-2.amazonaws.com/eks-cluster/python-app
    tag: latest
    pullPolicy: Always
  replicas: 10

goprometheus:
  image:
    repository: 675617749633.dkr.ecr.ap-southeast-2.amazonaws.com/eks-cluster/goprometheus
    tag: latest
    pullPolicy: Always
  replicas: 1

golangApp:
  image:
    repository: 675617749633.dkr.ecr.ap-southeast-2.amazonaws.com/eks-cluster/golang-app
    tag: latest
    pullPolicy: Always
  replicas: 1

postgresql:
  enabled: false
  postgresqlUsername: postgres
  postgresqlPassword: "changeme"
  persistence:
    enabled: false
    storageClass: "standard"

certificateArn: ""