apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eksapp-argo-cd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/junchil/eks-cluster.git
    targetRevision: main
    path: infra/helm/argo-cd-app
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true