<<EOT

apiVersion: v1
clusters:
- cluster:
    server: https://AF095182B62D885040C09FB54107D5E3.gr7.ap-southeast-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQU9UMzRERXJDVXN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeE1qSXdNVEF5TURCYUZ3MHpNekV4TVRrd01UQTNNREJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURSWmw3UzlwcjZUNWpuL0NzNTJucEFjckJJRmhoL2VKTHIwUWVFdTlYQWt0MWZ5T2pCeUU3TjI0ZDkKRWExVE85aDZSSUlaUU0rWjBIbU1ORUZUa2F5bzZOVTdydFRiVnVnYzByZzI1cVNpTmtCSVhqTUgzZUsrdW0xeApHUUlmK1kzNFNtbS9MMHhBM2taUVdaM2pjL0N3ajg4eDY1THFOcmcrQURzRC9jdTMrbThMdXVZcjNvWmZjZk0zCkQvcnlXQ01CUUFmR1NkZGlxeEdlSHEwUGtjbjluWFVFLy8zZzBPUWsrM3BQcTVZM0k4TG9RS0N1ZTZSeHJUWGEKUm1teHRlaEZ3Z3pIbWFMdlc2OWNjcVhyQllPMXlpc2xoVnQ3TFhjWGhpQjBSUVIyRnNxSi82cGhyZWJjaWpZWAp1NlZlTHI0Zy9PNnI4alVvOFkwKzc2RGFaOGxUQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSbDZCUTVaL1Y5OUh5Z1MzRjJFbk9FQ3g3eGFUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWdlNUVRU0pUbApyNW9HS3VsM3N1VmYyUXU4elpUUzA0d2QxMGs1QUR0YjYyT2tVQStkbjJGekcvNWZNTkZNV2ZNSkZtb0VHaHJ0CitGVUV6Y3pYN25WOXJOL1I4Y0VTOUd3czFtK0J1YTFiUm80dUxGbVk3Q1NyVjRxYjkzenVaY3RZNDhQckQ1ZW0KUXVMMmhwOWJvVlhTWDRxT3BnK0J0Qm9tdTEvSDBsN0tFZkFWYVAyUXJhQmMxemdVNkFKdy8zNEt3NHdObmc1eQp1aGdELzBqNGRPQUFtMlByU2pqT2FwVDNvZzc4MlFUZWMzSlhjMDZpanBrR1JzSGtPeVRRTnNWVm4zTDVkRFZ5Cm8xdko4Qm11ZlkzUlZBc0d5ajJsVEpacFgxRFVWdVFmZitLSUVTVnJNSTkyOVNFd0R3UVZ6MDNRSnNOV3Q2T1UKTE84SDJQUHVWWUxqCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "anycluster"

EOT
