apiVersion: v1
clusters:
- cluster:
    server: https://C16F905D944EDE728AAD59CBE3798DEB.yl4.ap-southeast-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZTIxVTdvVGtsTjh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeE1UWXlNakl6TVRSYUZ3MHpNekV4TVRNeU1qSTRNVFJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNmSkp3ckNXQXNwVWdXTFIvYTI3eFFlVjdaSkdrRGdzdWlOa0Q2YWJpb2oxcUxYaW05cHY0OGhGUWgKL1Q3c2l2bkp5MW4rMzRVdWpsR1hmK2hvRTdLZHh4eUdQVy9LS3JId1JVcTFzRHpEYldNYW9RbU1xb1NwOWxjSwprNTdyTVJGY2ZPUVB5Rzg2QmZTbkVWdFppa3diSHp5SzVzWUpWWFFPWENqWCt4R1VVcVNlK1JIRXI5ZUM2bFFrClFRZVNkVE5CL1V0K0kxZnJDTmtHbW5QTVlLTUZUQ3BmNEswMnJGRlhpTE8vMTlRUUxzdG9vdlA2Q1NJc1V1di8KcEl5NXM3N1VtWCthSGFrZ3Y4S245V2k2blZKd1JidEV3QzJtQlFvdURhdjkwbytheEpXYW5RWWQ3clJhaVpCego3Z2Y5QjFMNXd6K2l4NWgvc3FuNzVCb3VkV0tiQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTRmpiZXFxNkVId0F2WE5iU3pHU0ZGRkJ4SSt6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnQ4bGc4T2IwWQo2clg0ZU1iUnVUSWtISnlIdWY3UVhha2p4UE9RS0xoTEJTMjZRS0ZGSENRVzRXc01IL0swZkFFVDViMGp2WmhCClN0U2VrbE1abnN3VFY3Q0ZlTDJJMXZrQ0hMZTR3elgweE10emdZc05mVHRpVGpSaFZOcDNjNlBMOUhmQnkvYTQKVnlVaUp2WjZnVlJkb0tKekp3djF4VVhQNlZkeDZpcFZmNWF5N3RxbVNzUW9lN3hMMlprNGRwK0YyQmF4WjJDbwo2UGRMMTFVb1pjREowdW9BZ2syZ0pnb2VCMEVZM1habWZPeTF6QitoSm5YQ3M0WEJKTTFyRUJMMjVXb3N2eVo1CnZRQ2lQVldIYW9LU1NCT3pLdVFpWElwMHYvSTBjditmNVcyRThPcjFtTDBQVkVqdEZPSkhJeE9LS1Jic2djQ0UKdWRla2FQdHV6STN2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "anycluster"