apiVersion: v1
clusters:
- cluster:
    server: https://02E56C5B8BED97DB9AB87BDF76C2F200.yl4.ap-southeast-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZjRBbHVsVnp6bFF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBNU1qTXlNakU1TlRkYUZ3MHpOVEE1TWpFeU1qSTBOVGRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN0M2ZjNkdEYmpvWUYxSVBsMmJtZUd5TjJCZHZQSkRjRU1tUnArbmVJcGNwN3BMdjZNMUd3TzJlY0wKZWRHcnBMUFlmb0dLV3V5aXd1U0t0dnZrUFRZejhBSUNDUkR6dFpPNTgrTXZKbFl2Y0NFNm1pQnYvWC9nRDVFZAozV1dCbHZ2REdrZnpja1lDMlNFSkFFUUxjWENiT2djT1BrSjhrVlpIWGhyekJCblZ6Ym1XQnEyQTd3a2g4dStwCkF5VVpsSW5UWDE2clZHMSttbXNUVEZ0UGh5ZFlENmwxbyswN1dRWG5MMGluUlAvV2FJYzhYREMyWUxVeXRENm0Kck5rcWxNZjcwcEtTazQvOFdXUmwxdCtTMk52emwwVmpCQlRVWGhsRittREhibG9Bd1hOc21qaUNWejcvZGNhTwpSenJPSnFWaW5FNnlpY1I5dGlNcXdSRnNoNzhOQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTSGNDSXJqVmtCeEdlVlAzcHNVRFViYUJUN2RUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmVyV1ZlL29nYQpZUUUzYVZycUhnWlBtcnE2V1lBTkYrSHE2ZXBCQmhCZDdRTVZtTFR6TjloaDNsSy8rYko3dVZjOTVEMnhHZnRXCjA5Q291NVlKRnQ2ZTdqTDFRT1R0bG8ycjhTNG12UVRUNHhJRndVdTFrUlplSWJtc3lhNmFtcmpaUGc3Z0tGU1UKaGZKNW9YeWx4d2VVczdXNGdHTCtjZHJGSVNyMm5WN2FKZGdsbDJodWJNS0xnY1BXZUNxSmk1N3ZKMnFjTzIvYgoySUFEVU1HbTZ2aG1zejc3WEIyWUZaWGJhQmFidEJuWUZUNldlWXpTSXJ1Ly9hYmRvUGVZMEFaQ2N4dzA3bmlNCmhocjdkZ0FwOUE1eWJEREdoYlJ4Zzcxd3RkTEtLNVpKMnBoNmJZdzU0RG90eFFYdGd5dHNneDk1bVNQcVdLbFYKTzdUS1FVOXduSTh1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "anycluster"
