apiVersion: v1
clusters:
- cluster:
    server: https://2F52A3E1A7D4E0145E27F321B81405F2.sk1.ap-southeast-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQnM1bEUwSTBSRXd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeE1Ua3lNalUyTkRCYUZ3MHpNekV4TVRZeU16QXhOREJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNaZXNKcWcyRTJHRS9lNHVsVURpai93dkt3YWVEdWZpRGJuZ0Y3Rk1xVnZjVXZiMTA2ejArZ3lHYjcKRVJ4aUNXYjArR0dJQ3Z1UmdYNjJGNUxRS2VwZmJiMzBBREQ1Vmo1OFdtYmo2VWhEWllDdDZramlCV3pYbWFPegpFbHN0azlpRVpOUWYxaElrUVRSM3poTG1VT1VsTllPajg4OUptT25oOHZUU0R6WmhwdHBYb0xMUUxyWFFYSnBECnl6aDlnalNzZG9GeDd0QkFpNE9YNkVqZlRDNytEMFprU3lJRDdMVVdJb040MkVWblZ3YWZnZWRHb2dvQWlrMmwKdlFPY0w0amlrQklDdmd5Y1ZOaFJ5aVhhWXN3cWtVRFlubWZQZTVxekRveUFsb2pMMW5ySWlYWEJkMERrR0I4agpZWWZYaVFLYVg4cHdQVjBqYkF4MmZLcWxWZXBEQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSYnhGU1NJVFd0RGpLenFSNDBtaUdsZE5KK1RqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0hsTCtVazBJNgpYYXNyQ1BRbUdUSmk1M295dzJUTm9ydWpSa1crWGx1SS9XOHorZ3N5MFZUWHhJSm1wOU5GN0R0c0FBTThQZVl5CmpUTFcvUEVJRWlXVWlZUy9xbmtFcjNnNnJ1VFlaQWluZGpVSDhJd093UkxIcXV6enRmWG5ETWVmMFdQWk41UGYKNElPd2dONXhDcEFLRk55V3RWallpbzlTWDN4bjJ2YUNQMU5ySGNCbjBXQk1ZUUtCM05ISHgyUTNacWVETEF2Vwp2UmJXaFRPK24ycUJOeitINVhXeWdFQlI5UzN2NTFCRTcwK0llLzNYZXNVcVZESmJhOEpoUjV0cy9ZNDJ2QWNHCkhoUjk5UEFUOGlVbjZjRVI0cyttVTZWYVBtZ0drTmtrZXdXSW1sME80WVl5OUtZbVg5NEpUNE5RSDdualBtZE8KU0pDYUsrVkdOc3VxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "anycluster"