apiVersion: v1
clusters:
- cluster:
    server: https://0E5C9F73F84F54F77F6C030252E6A84C.gr7.ap-southeast-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUzY0YW5GUXplS3d3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeE1qUXhNRFEyTURGYUZ3MHpNekV4TWpFeE1EVXhNREZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN5aUh3V2M3MGVKTG1rUndDeElvdXNrcDhqdzNWWXNrQlNFbVVSdUdDd2ZxNGY4S3l1OHFwK21YdDMKL3BDTnZxaFU2QkM5WFNBNDI1MzdueXZldjVNdnJTNnhURDMvL3NhalcyOGRaTFpYbitNYUx5V0NORTMrNU9sRQpBRzFKTURiWXBFNUhwM0RZRnZiZWxyVXdRcW1lR0ZtMGlqQm1TNkN1MTJpTUs1KzV1eHlNa1daZEZ1YnZYeEVmCkNra2E3ZE5mVzAzUmw4VUVLczlsUm51RXFQZ20rQkw5cVFuWTRtT0VaSEdBazB2dGFGMkdpdW01Rk42MmoralYKdVJPVUtySnhpQXNmYjI3dTc0NVE3R1UvZmVxNTc5a1orekV3bENHL0xaQUJ3MnhMMG9ZQndjeU93bjhYWDhWNAp5RUJ5Q2ZUemVNUzE1SzExNXluL3IxbGVxQnVEQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTOHB6aVFlczZQeW5UUUVUMG1rRGYzVkdhYUFUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2I1SXNKUlE3bgpwbkh0R2k1dnM2ekt4cWE0ZTFLMkJHRm1FZmdZS3o2T1pVS25vUUU5S1dRZEZzMTBtbnZGUzl3V0doNklBSzR1CllLbmpUWmRtRXhTbmtNOGY0d2piV09RMmwxcEthbEdMa1lMUmVWNmdMaUgySkxHT0VaOXRtSGJ3U2RZT2xuS3UKb0pQdzRTTC9Sa0xkbjEra3ZLdFkyaXdBMHhsOWgxbnU3VU5OSEFRNTdWZDRldklHakhNdVNCcHE2d2Z3OFM0dApIS0ttVnlIcXRUQit0QUtYc0Y5K0o1aVBaM05uS2t4SWFyWnVtODdXc2paanl2YnZnTllWWUhsaDFGU0QzcnBQCmJqdkg2eUM5eFhadTlPN0I5QXF6ZFEzUmxIdXBHNWNtQVFLajdTa0xCMGQ1bjBjeURseEgxNHpjSEp3Y3NwSC8KNVV3NVo1T2JZWmxxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "anycluster"
