apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJT0F5RHU0TE91TkV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBNU1qSXlNekV3TWpGYUZ3MHpOVEE1TWpBeU16RTFNakZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNoWG9nY0E2RjUySzFTVjZ1MHVlVms0SUlHYTNIQ1dIektXK2Vqc3QyWjFQSVNEK3pvTnZQaml0cEcKcmlsTzNEdURZTjJsWW8rTGRBUCtBWnhKK0dhb09aN2h0K0F4bVFCb3JmbENQZkt6WWd2U2pUb25teE1zM0luTwpTYjFCYkNQbmpZRTE5b3l0RUFMLzZJcUpxL2lZdnVjM0tNTWI0MDFJRmtEd0U4bU96cE1jUGpVMkV1V25GVjNOCjFWdkZESVBCblV2b0Q3eFpjU2s0dGtBWTcvNVkvbnpkNGt4VW90TXh3LytlM3pCTDJicnNiRDNCKzZuY3pFU0gKcDNHKy8rV1pMUlFvN0lRTU14MTY2Wk5SWFFQeHQwY1pXVHhsTVRDVW9PYWhubFdHcHFYUklBWEdydk9CbEo3eQpBWHBGYmFnTEZTdjhvRXB6ZCtoSU9yWXpFRjdMQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRWGlOWjRYeDBHSkR2S2VOSkhFWUl5aXVMNUZqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2JpWFhqWFdEbApBWXJjTWpmbU5uQ0tIN0V1Q295YVUrOFk4aGwyZ1B5RGl2anBkY04zcE1YRXBaSEQxcjIwMFBvUmVIYVdJd3dsCkpGeGdvRENpRlcwVjRySGVXbWJ6dm9kcWRqOTNqZFhkNDNsK1pQRTdtVzhVbS9iY2srRXdpYmxDbStvOWJTRFYKNGd3dCtya2J5R0VvSUNFOTBiZk9HeDY3NkhJWnM1VDZyakFxbVJIVkN1akorbnFiTlpNZnljMFlTZUNGSGtpKwp0RlNpeENTWFpRdWpFcE8rU25UcEhwZ2htU2dLbVBkMHRRelVjMFViQXlDRHQxMkYwemNRQWlEa3RXbjdjS1gvCmdyL0s2NGtyT3hqMjFuQUdXRzNCM2VGV1dzaE4xM3BPcmVZUFRRTXVzRnc5eGRpZmg1ZUs4Rk1ZajRqdWJOeGwKZklObGdmaHhQdSs2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://AEBBCFEBD2120195411972CA984B07A6.gr7.ap-southeast-2.eks.amazonaws.com
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: argocd
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - anycluster
      command: aws-iam-authenticator
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
