apiVersion: v1
clusters:
- cluster:
    server: https://B227D9071156E5DDAFAFB601FF3DCF8E.gr7.ap-southeast-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZVd1czAra09Ga2t3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBNU1UZ3lNelE1TVRWYUZ3MHpOVEE1TVRZeU16VTBNVFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURIZkFFQlNyLzVEa29XNHdONy9sVnN3UmM0SjR3TVU4R0ZlbGd3WWlsWnZjZjgzN3J3b2VNWkRGNlkKT3czK3N1T3dmcWh3ZWZIUzFXYWlZM25uZ1JmUWxSZFpGMWVYK1M4QUFUYUZwZkNTZkUzYjNURlhDZFRDRHA4WAo4NG5vVks0bkZkc1dCWWFvSVJyaklEMm9aK25EUjFmNmE1TXRxdTdWMVlIdEFhQXlhaHBPRzFzQWYzbGVUSlUvCk9mV0JWWnphTGJrYi94NHJVZnRuZitIWVBtTVY4SjM3Qlk2YVlUcWRjVEtaaWFpdU9BZElWc3lSbmlVd2w1c3kKd1R0dEVhcFR2S1JlQm5GU2dTU2NwYkNUVWRuaHlSYTM5K2hWZW5BUy9CZVRVVzJjcEl3M0daRkVzRTdoZ0MrVApTamlYVUNOMElPNVZUczE3U1VNS24rcmo2UU5EQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTRFFBQnBUR2NFUDNRRU5IV29GR21YS3RUc1pUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQndRcU9DMXZaSQptRlVhZWF5R3JHd0p3Z2pPdmRKZSttMEV3SE1pZHROTkFsWjNCVDZYZGdHcVQ2ODZKeUFScjl0d1dwVXVkSWlICnN5bUp2RUYyZ0J5L1pIQnB3SXNHTnU0NUh1azAxTWZVMGdyY3JIUGxSeXNWV3licUdDR2cxd0VFUHdpU0xCclUKMmpDOE9PbEhlVXN2UFhoMGcwcCtkNHM1Szc3UHZ2aGtDVEtZcm9JSUR1S1o1c0NndDN5Y2RndnFaNklHdGFtRApkRkRIeWdZTVc1TWFLWXUyUE9LdWFsc0poSWlaRzlJdDB5QmJQb2I2Y2g0UWhkUTZvNkRSUUZJcy9OeER4SWVOCi9FNlZuS1IvRDZhdlVZTTJLMnZMaFpnQi9LRm9LUXBTa3BSZGxDMjErWWRhTmdLanNwaXZyS1l5eW9iZzBweXAKaU8ydFJpNkt6elBhCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "anycluster"

