apiVersion: v1
clusters:
- cluster:
    server: https://4C04A2980CB60F8C1654B3468C94A6AD.gr7.ap-southeast-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1Ea3dNakl6TURRd04xb1hEVE14TURnek1USXpNRFF3TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSiszClh2dTBVakpCVGV1OWIzL3RtbU14NnhPUWF5ZVlXd29GcUl0N2Q4U0dRaWJBVEs4Tml4VDcxcHVjN2ppVkdaSnQKSy85b3VkajcxTTJNaGsxTGV0SFhadWRiNzNESitXaFdIczlkWStMS3o0R0VyVEVPODMxK0NKTFlMbzlwSnc3NAowQkEyN0pNajJ3YzIwMjVZbWtYays1NE5Wem4raHV1dXp1RE1aZFVGNnJGS2N6WFlCc3NUeFpoVTdtWU9WVGZsCnhXKzZJSWxCVklCTkpEWld4dDlia001bjlBZ2hYK2xjRUxBT2FwQTlWRnAvYlB2K3gwSytDZm1FaHVWUUFyS0gKSVlzR29YYis3b09Ua0xYS2M0U1VEd281WU1NcFFrdGRyelVFSlVQOVJxVC9yckVOd3FHRU9DRW44WnhqZnZqZgpDa01tMFZKSWZManFCQUo3VHlVQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZCNTBJRGllRFRNZ2Z6OEpjUHdKemp5SDZvNmlNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCOXhvdTcxVjI3WHNsVG1aT1V6NVJzVDYxL25XZzdQVnNFbldldEtNc1FBTGVRcC9LWQpHTlZ0TmU0SHdGTFc3WVo5N2pTNTlzdWd6NHpuWWJBZGppLzR0OStsc2UyKzJ1c0VOaHdmMGRJK2lwc3QxalJWCmNweXkyMHhDZzhYaHpIMWlnbjlRWWx2L0l2Z2FpcmhVckdQSmpVV1NzVGNsWmovbjJXWkw3dHRrVkwyS1hRbW8KZ1czWGIveHNSeG9pUmNiazNwc3lvY0RtTmpjSFdjbkVLaC9ZMVcxRTRWbDBBaTFvVU1iQUN4UnhkaWhiZzJyUQpEVVFRRnBrZjRxbkp0VUp5am9zN29ENVR2WjVxRmdWM0VHMnZ4TG1ZeWVoRElmK051RkxUYkdnUXNURSs2dmZlCjdyMjIrRGJlbndoaHN0Sk9DVVpBQnMyMURrRE1IQWxPVVp3dAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "anycluster"