apiVersion: v1
clusters:
- cluster:
    server: https://70264D52E48D38B798283CB9D7BE495B.gr7.ap-southeast-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWm55TE9EL0w2Qkl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBNE1qY3dNelV5TWpaYUZ3MHpOVEE0TWpVd016VTNNalphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURDKzhHdFRwVVFaTHdWWkpkYjREdUQ5TDNKV0ZqdWxkQi9WdkF1alBJOTVWNDJqY1BTQitqN2NTcEoKYjRCeHMvVFZsa2gvbEVDd2prZUlVdFBwdGYvUGZKOUU0NXBqdnhVUXNGUVhJZWV4VHQrYTJnYXd1M0hTSENxUwp6UjA4OGoyNzlmNW9vS2FqZVBqb0pXbjE3d0tuMkFVeDZyc0ZKTzhSR1AxcVN5bnZzMElOZkxYVy9EZDlTMnZXCjFvU25MbWwrMFR3UzFMRkVHYzd4Ty9uYnB4YTFkemwxKy9pQ0QyM3NmQW9jQWRxd04za2FwanpMNWV0WklMcHcKWS9vUzUxcWl2b3RTdVBYN2VXa01kVGV0M05XUHNsVE5kSUJNQ3ZUTCs5elVsZFhwVFhQK2xnYW1udFhaU3FybQoySGxFcGRqMWJ5bmpzMVV3ZDhRZmxOd2VFTjJoQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTdVkzakR1N2xNUHcxN0IwQ1U0SlZsVDN2Yy96QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVJXK0M5bVlocQo2NXl4U1pLNjVlUVlBMXJMRkZBTVhiR0VPeUZxT2pmbnEzTFNld21mOG1nRW4zUktOcUhXNGxMNnFWWWxiVVhTCkRqdjdLcFkzb0pvVUROT3lPT3k0VmJteDRwOGJLK3lGNmtoZ0J4VzFNUTFsQTBKY3dLeno2cjlWbklJZkxwaGIKMWUrTVJxblZqQVFoZFZ6dVBEN2hsZzJmNjN0YXM2eE9SV1FiOXVhZk9nYXd2UHI5M1VQbmZoTUlrOHQ4OERodwoxMWhWRDRjL1JIeTd4SmppZkFKWjNGOEd0MkFHV3R6UGptK3pYbFk2di9URWJMNzIxS2Q5b1huRVpMSHpXVUlnClFVOXRtSm1YcEJTaEhOR0ZtaUxpNkQzUmRJV1lQQ1dPYjhCUTdiZG9oZjdvTExvYXJxSm43Y1VwbGNYa1NlZDAKdzJ0R2RLTkRrTTQ0Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "anycluster"

