
apiVersion: v1
clusters:
- cluster:
    server: https://32EB3227146734F60D16E778F36F99C2.gr7.ap-southeast-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EWXhOekEwTXpreE1Wb1hEVE14TURZeE5UQTBNemt4TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWJWCjI0bGJVaWFWSTVHTnFGNFgyOFF4QVE0QUhVd1ZoNnU0M1JQbXY4aE1zOUdoS1pSVlljWUFFN1poN2czS0VBQmgKbVNGQzdwdlY2T24rQkMwSlA2cHh0SzVRN0JtWXJLdUgwL3Fzd29xSm9xcUx1YVZ1U3ZYK0Q4SW96aDBYVEpyMAo4QmVhWG5FMXRqTFB4RE9PVXBDWnQ5YXJmTUVlWGdpMWhiZ1ZUOHVGeHNIamsyd3Btc1BPY1Z1ajUxM2hNMkdFCmIydnhzUjhENElZMTlDQ3V5NFY0amoyd3B2WE8xb1RoVWxmdkRXV25TanpuVFUvRU9zZHZEdUs4aDI1SlNHT2kKcmFZdDF1SmZrM2lwK0ptSjNlS0l2bExnQlhJS0lVc2VBU083djJlNzE4WklmL0tHWFM5MkNTa2xiZWlTc1NTNgp4N0x6b3dESTQwYTF6STFkNmUwQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZHM1dzSGh0VG9MYVlFMWc4Q0lIejh5YUtrOUpNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCR0VlejBkK2RLQThJMFpwK29EY0tyYjNXci93N0dtczJnSXUwRkJaSkRCWDRSck55cgo5dHcyWS9kSGxqanRqUGRkaGxyRU5qMmQwcHRnaG1oNzJJaGk5V0tIR1BjTW9NS1MwQndDdXgxaUU4THUwcDlmCjlqa3pleUQvQWY2VzZxVXBEV1pDbURwelFvd2RJNy8zLzlLQy93ZitGTHgxbldhNUdMU1NvT29uR3FRWHkyRnYKMXFydW9qMlU2eWRrV0ZGZENuNVdnZEJQWi9IUDBrNENDV0xBdWozTTlsRXZiSzB6M2pDVDJWZ1BKK1lSQWQwcgpSYWlSTEI5ekp6SnF5THdaTzZ4SVA0SXpSYVQ4RjVoMUhma3ZUT1IrdFU4UklWM1VSbWF6Mmd3Zm5rL1Jadm5RCm9xMXJaSUwxamhGcXhYdnl2czBFS0ovcUhVWTdVZGx1NmtLRwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "anycluster"
