apiVersion: v1
clusters:
- cluster:
    server: https://95396F8EADD2D195B3555C8AAA0FC8D7.gr7.ap-southeast-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJVVhYUktkU1FSUEl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeE1qTXdNelF3TkRGYUZ3MHpNekV4TWpBd016UTFOREZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNxQXFPVlY4d0hNbXdVd2FQYUFuN1ROOUR5K2twNDZWcnl1aTdWRzNEbVhhYnlLODZ4N0N2NFlmakIKRDNJNVp1czR4T29OZ1FuY1V3TTBzWDQ0Nmh3VFJBR2l6M2kxR1FIVVdIZk9nZVVMcTgvUlBtS0RaOWlobC9GcgppcElVRjdwZkRhV2R1UVlYellUbStTb2h3NEpvcS8wWVJyeE1UZ2tzMjE3VWx0WTlXam5id0NtNzhJRlRPRVZICmw2K3lCQ041UHc1cHNFd3M3c0FUeFZicy9HbUNGMFRoamNwZDVPWng4K2Uvc2RWYXp6ZUk0Uk5HS2hmWlBpZm4Kdmt1VG94THRuT0d6ZHVUaG9kUnFOSEw0cEtyYnNKZVRIcEhNcXY2WitsUTR3c3lUUE9lWjM5cnZERVpwMlk5ZApzQUZFa01xNjVyNTVvb01heCsyZFRrQ1lCYnpQQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRRW9wSUhFY2JkZzRhTVd6QlRRQWVvYTVRemJEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkFjU2FHZ2ZyVwpiSDR2bFF1R0lkd1U5OFJrZjlpbXZWeTJJaHQ5UWNkNlZkZC9ndVl1WnMwc0V3bC9NOTl5cGFLRUVWSGJHbmRmClcrVWRnaU9VVEl4Qzg3MFJjZXhPdjJ5ZVVvMVhhRGpodXVEMW5FSU9jQlVxcktSeGZYcGxlODFIOGhzdzZRVEYKcEIzNzNwVXRwM29kT0pLMzA3VTFjWEpzY0t6T215clRWYjNaQXQ1ZDJTUWlMWFozS0ZLeDdScW8zSVRhdGJPTQp1Zmxib09qZ2UzNk82V1RmNGdjZzZBczBrWXlCL1NyMWdwSkMyeGVPSlBTM1hkYWdxby82RXVXVmgwcEhrZ3J5Cm5BbG5JK0srQ1RlK2hTdFNLYlRNSTQreDg0aGJOQzlCVFNZeHNxT2I2clZ0bk5xR2dxcUllSFVkU2dtT0dyNGsKbXZLTGYzeWlpTHVFCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "anycluster"