
apiVersion: v1
clusters:
- cluster:
    server: https://2E069EFDE9937C4A3372651E0A2B6728.sk1.ap-southeast-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EWXhOakExTlRjME0xb1hEVE14TURZeE5EQTFOVGMwTTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS2lyCnZUbUEyaEVPd0VvSzNZWWtLbGx0bzB0bGVNclc0T2xXUFdXdlhIVDZjOFJQbndtdDBNU2RwUVBtaU9tQlYvSjQKSmlWWExFcmdmc2pZWnRYZnFzV1U3N0lqVWtSckRwb3hMYWZRS1VRMUNOUU00ZkUrL25sNnBDNUZMVzY4SWNRYgp1OHJGcXdEWm1xcVZWOW44dDdPTzlMMWUxK3IrNFlmOEgzNlpGTEVsOTJyejRWSjFOZHlLT3dUcjBIYXI5UGZlCjhYY3FXb3RPWjZzc2VtekdWeG9uMzZzWHNLVUNPK1pKTW0vYVlEc1g2YjFSQ1E1MVNaaDd3VU9HaEhNd2M2UVEKM3dONmhGdnE4SzBwWUlNYVpPT0ZMMEpHV0t2RHNSZmFmM2hoNFppVUFjL1hvOUhJQTdyVE13MDJUV1dZK0lEdQprRU9YUVZBSk5DUGVpekdKOHVrQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZCamlEZWRZZnJIanErR0ZTNmU0TWNvc2ppdjVNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCSkJrbjlFaVRaQVVmbDVYbng1SEczRWNmemNUaFluN0c4MVNDenJZSlg0VHJucjdLNAo5VEM1WDJYYk11NU0xN1RGRnExQTVCQzZiclZBRVlXdldndTZDZW45aWc4OVZWUlhrQXFpMFhuNzVaMVcxMUFxCmxLVkxJT3VhRW1IRTBmZXZxQStLdzRFSFpmNUtocmtMa3hUb29Icm9xOFNEYjdPbXhtQ2RLdWhxUnMxeER0cjEKMTQzcENuSUpRNDh2SE1xaHdvN2dPZTA0VkdYRVVMMzlWRkxnL0VUSFRCbFMvNUVabjNsK2VyQ29TNnc5bkt5cQpjOE44T3EybVdkTmQyY3dGUVVHckl2S2NvcjF5aWgwbTJDNVJ1QmxJNzNJeStUS1RSeGNXcDd5OXVPblRaLzRYCks5VWVUNUZrTjg1SU14Mng3VHhxTnJxajIvRFJHbWduQTIvTwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "anycluster"
