apiVersion: v1
clusters:
- cluster:
    server: https://3121192EA308794A3DCF99EB520A6F4D.gr7.ap-southeast-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSStFcjc2QlJ5bDh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeE1qY3dNekE0TXpCYUZ3MHpNekV4TWpRd016RXpNekJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURzMU5MeTRQMktTQ0Ixb213dU9tNDBvZXMvbGR4SmEvRy85eTUrT0lULzJQQTN3WnhCeXgrS3VnSU8KWnZHemdCSXNUUFhZM001QmpWRHFUS05rbm83RTJRbktpQm1jWUZzVjVFL0hNRUtURldjWWYxZEdobVNsSDdXRQp4TFBrZVJseDdUYkdpcXdSSndrTS9Zczd0ME9qZVFhbVdFR2JCbzRqOVBRZUZOUU8yU1JWWTNLMTNSSHE5aDdhCjc3UldUcGJyZmVtaldJTU44TGFqR0VENnk5Mm8xREx0L051RlpoVHZnUjZtV0xvMjMzMDZtUXFHZjVxWThMR3MKMUxVUDNYNmlYakdWbWcwdkViNU1nL3N5aHBLQUtnV0ozMGxWdnZBZTZzbVRXVFBicGJkemE0cENzbWxaLzdvbgpMUlJidGwxc1BkWmw5SEovWXpFM2poTFZjQWdYQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUZGxCcnBsU0lSVWRkaVRkMERreXFOUUEvSnpUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUF5cXVPTFJrdgpXZDZvZTBxWk1Xam5MZzFzUEVxQmowbWp6Z2lHd0RTUVdYMDhFTy82Z25BN2FxYy9BbTJIWmkvNE0yY2FCVTY0ClYzaUJTVThkOS9qNVo1dC92TjZqd0Y0cFN2b1RZWDR5bEUzZnJiSC9hZFo2bzRzS2o5Z2ZTVjhRWW8vVllZc3kKU2w5dFB1d25XalBjRlRqVmh1bFVCMUlwNkIyWVBZdTNTVTllUVRXVFlkNEsvYzk5WEh4eE8rei9iSFBsRTM0UwpxbzJVaS93UVNQcUxyRVh2bHZvVHVOUVR0NEhXK2QwNGIrdmFpbGdZbnAvcTlxQXdTMlBUdlJMckVjQmxDYUl3CjNkZDJ5QnB5WXE1U1lQcGlOdGcrOUd2WHU1VWZSekhkaXBHNVJXTmtMV0FNcmFTMEVUckpwajdNMEJITXBYV1EKRlUxWm41MTJERnFOCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "anycluster"