apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
data:
  vector.yaml: |
    # Set global options
    data_dir: "/var/lib/vector"

    # Vector's API (disabled by default)
    # Enable and try it out with the `vector top` command
    api:
    enabled: false
    # address = "127.0.0.1:8686"
    # Ingest data by tailing one or more files
    sources:
      kubernetes_logs:
      type: kubernetes_logs
    sinks:
      stdout:
        type: console
        input: [kubernetes_logs]