apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vector
data:
  vector.yaml: |
    # Set global options
    data_dir: /vector-data-dir

    # Vector's API (disabled by default)
    # Enable and try it out with the `vector top` command
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    sources:
      kubernetes_logs:
      type: kubernetes_logs
    sinks:
      stdout:
        type: console
        input: [kubernetes_logs]
        encoding:
          codec: json