repositories:
  - name: stable
    url: https://charts.helm.sh/stable
---
releases:
  - name: eksapp
    chart: ./eksapp
    installed: true 
    values:
    - certificateArn: ""
  - name: istio
    chart: ./istio
    installed: true 
  - name: karpenter
    chart: ./karpenter
    installed: true 
  - name: monitoring
    chart: ./monitoring
    installed: true 
  - name: nginx
    chart: ./nginx
    installed: true 
