nginx:
  enabled: true
  controller:
    replicaCount: 1
    config:
      use-forwarded-headers: "true"
    service:
      type: NodePort
      # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      targetPorts:
        http: 80
        https: 80
