apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-golang-app-service
  labels:
    app: {{ .Release.Name }}-golang-app
spec:
  ports:
    - name: tcp-golang-app
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-golang-app
    
    