apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-golang-app-v2
spec:
  replicas: {{ .Values.golangApp.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-golang-app
      version: v2
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-golang-app
        version: v2
    spec:
      containers:
      - image: "{{ .Values.golangApp.image.repository }}:v2"
        imagePullPolicy: {{ .Values.golangApp.image.pullPolicy }}
        stdin: true               # required to stop early exit
        name: golang-app-v2
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi
