# permissions for end users to view golangappoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: golangappoperator-viewer-role
rules:
- apiGroups:
  - app.stevejcliu.io.stevejcliu.com
  resources:
  - golangappoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.stevejcliu.io.stevejcliu.com
  resources:
  - golangappoperators/status
  verbs:
  - get
