prometheus:
  server:
    persistentVolume:
      enabled: true
      storageClass: gp2 
      size: 10Gi
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.stevejcliu.com
  
  alertmanager:
    enabled: false

