{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-goprometheus
  labels:
    app: {{ .Release.Name }}-goprometheus
spec:
  gateways:
  - {{ .Release.Name }}-goprometheus-gateway
  hosts:
  - "web.stevejcliu.com"
  http:
  - match:
    - uri:
        prefix: /goprometheus
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ .Release.Name }}-goprometheus
{{- end -}}