apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-python-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          service:
            name: ssl-redirect
            port:
              number: use-annotation
      - path: /python
        backend:
          service:
            name: {{ .Release.Name }}-python-app
            port:
              number: 5000