apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-python-app
spec:
  replicas: {{ .Values.python-app.replicas }}
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - image: "{{ .Values.python-app.image.repository }}:{{ .Values.python-app.image.tag }}"
        imagePullPolicy: {{ .Values.python-app.image.pullPolicy }}
        stdin: true               # required to stop early exit
        name: python-app
        ports:
        - containerPort: 5000