apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-python-app
  labels:
    app: {{ .Release.Name }}-python-app
spec:
  gateways:
  - {{ .Release.Name }}-python-app-gateway
  hosts:
  - "python.stevejcliu.com"
  http:
  - match:
    - uri:
        prefix: /python
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ .Release.Name }}-python-app