repositories:
- name: eks
  url: https://aws.github.io/eks-charts
---
releases:
  - name: eksapp-aws-load-balancer-controller
    namespace: aws-load-balancer-controller
    chart: .
    installed: true
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -k
          - "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master"
