apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-clickhouse"
  namespace: clickhouse
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
spec:
  ingressClassName: nginx
  rules:
  - host: clickhouse.stevejcliu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eksapp-hdx-oss-v2-app
            port:
              number: 3000
